### ISSUE TITLE
GermaParl Download

### ISSUE THREAD

**Issue by haraldo1337** [PolMine/GermaParl#18]
Hello there, i hope by any chance that somebody could help me and some fellow students with and issue regarding GermaParl.

After downloading GermaParl is not avaible. 
With the code provided from the main PolMine page the output is: 
Fehler in cwb_dirs[["corpus_dir"]] : Indizierung außerhalb der Grenzen
With the code from the issue section here (#16 from 31 Mar) it downloads it but the output is, that it will still activate the GermaParlMini corpus.
In the most cases it happend after extracting the tarball.
We got this error on Windows and on MacOS.
(_The download of the Europarl corpus works fine_)

`if (!"GermaParl" %in% rownames(installed.packages())){
  install.packages("GermaParl", repos = "http://polmine.github.io/drat")
}

if (!"GERMAPARL" %in% corpus()$corpus){
  GermaParl::germaparl_download_corpus()
  use("GermaParl")
}

... extracting tarball
Fehler in cwb_dirs[["corpus_dir"]] : Indizierung außerhalb der Grenzen`

**Comment by ablaette** [comment]
I feel terrible not having answered this issue earlier. Please let me know whether the problem persists. I have reworked the download functionality many times, I hope it is stable by now.
