### ISSUE TITLE
germaparl_download_lda() doesn't work by default

### ISSUE THREAD

**Issue by Studentenfutter** [PolMine/GermaParl#7]
On both Ubuntu and macOS using 'germaparl_download_lda()' without arguments returns an error:

`Fehler in sprintf("file '%s' is not available") : zu wenig Argumente`

When manually defining a single value for `k`, e.g. `germaparl_download_lda(k = 250L)` the function works however, as soon as two or more values are combined `k = c(100L, 250L)`, the same error occurs.

I've checked for possible URL-errors: I can download everything manually from AWS just fine, just the 500L-TopicModel at `https://s3.eu-central-1.amazonaws.com/polmine/corpora/cwb/germaparl/germaparl_lda_speeches_500.rds` returns _Access Denied._

**Comment by ablaette** [comment]
When we moved to using Zenodo to make GermaParl and LDA models available, the function has been reworked thoroughly. The issue seems to be gone. Please re-open it, if necessary.
